'use client';
import { useState } from 'react';
import { track } from '@/lib/user-data';

export function PartnerLeadForm(){
  const [form,setForm]=useState({name:'',organization:'',email:'',phone:'',partnerType:'hebergement',message:'',website:''});
  const [state,setState]=useState<'idle'|'sending'|'done'|'error'>('idle');const [message,setMessage]=useState('');
  const update=(key:string,value:string)=>setForm(v=>({...v,[key]:value}));
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setState('sending');setMessage('');const res=await fetch('/api/partner-leads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const data=await res.json();if(res.ok){setState('done');setMessage(data.persisted===false?'Test réussi : formulaire fonctionnel en mode démo, mais demande non enregistrée tant que Supabase production n’est pas connecté.':'Votre demande a bien été enregistrée.');track('partner_lead_submitted',{partnerType:form.partnerType,persisted:data.persisted!==false});setForm({name:'',organization:'',email:'',phone:'',partnerType:'hebergement',message:'',website:''});}else{setState('error');setMessage(data.error||'Impossible d’envoyer la demande.');}};
  return <form className="panel partner-form" onSubmit={submit}><input aria-hidden="true" tabIndex={-1} autoComplete="off" className="honeypot" value={form.website} onChange={e=>update('website',e.target.value)}/><div className="form-grid"><div><label className="label">Nom *</label><input className="field" required minLength={2} value={form.name} onChange={e=>update('name',e.target.value)}/></div><div><label className="label">Organisation</label><input className="field" value={form.organization} onChange={e=>update('organization',e.target.value)}/></div><div><label className="label">Email *</label><input className="field" required type="email" value={form.email} onChange={e=>update('email',e.target.value)}/></div><div><label className="label">Téléphone</label><input className="field" value={form.phone} onChange={e=>update('phone',e.target.value)}/></div></div><div style={{marginTop:14}}><label className="label">Vous êtes… *</label><select className="field" value={form.partnerType} onChange={e=>update('partnerType',e.target.value)}><option value="hebergement">Hébergement</option><option value="restaurant">Restaurant</option><option value="activite">Activité / guide</option><option value="transport">Transporteur</option><option value="office-tourisme">Office / collectivité</option><option value="autre">Autre partenaire</option></select></div><div style={{marginTop:14}}><label className="label">Votre projet *</label><textarea className="field textarea" required minLength={10} value={form.message} onChange={e=>update('message',e.target.value)} placeholder="Présentez votre activité et ce que vous souhaitez proposer aux voyageurs Waka."/></div><button className="btn green" style={{marginTop:14}} disabled={state==='sending'}>{state==='sending'?'Envoi…':'Devenir partenaire'}</button>{message&&<div className={`notice ${state==='error'?'error-notice':''}`} style={{marginTop:14}}>{message}</div>}</form>;
}
