import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import Link from 'next/link';
import { curatedAttractions } from '@/data/cities';
import { getAttractionById, getCityBySlug } from '@/lib/server/catalog';
import { ActivityMap } from '@/components/ActivityMap';
export function generateStaticParams(){return curatedAttractions.map(a=>({id:a.id}));}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const a=await getAttractionById(id);return a?{title:`${a.name} | Waka Tourisme`,description:a.description}:{title:'Activité | Waka Tourisme'};}
export default async function Page({params}:{params:Promise<{id:string}>}){const {id}=await params;const a=await getAttractionById(id);if(!a)notFound();const city=await getCityBySlug(a.citySlug);return <main className="container"><header className="page-title"><span className="eyebrow">{a.category}</span><h1>{a.name}</h1><p>{a.description}</p></header><div className="detail-grid"><div className="stack"><section className="panel"><h2>Informations pratiques</h2><div className="result-grid"><div className="stat"><span>Destination</span><b style={{fontSize:20}}>{city?.name||a.citySlug}</b></div><div className="stat"><span>Durée conseillée</span><b>{Math.round(a.visitDurationMinutes/60*10)/10} h</b></div><div className="stat"><span>Niveau de prix</span><b style={{fontSize:20}}>{a.priceLevel}</b></div><div className="stat"><span>En famille</span><b style={{fontSize:20}}>{a.childFriendly?'Adapté':'À vérifier'}</b></div></div></section><section className="panel"><h2>Fiabilité</h2><p>{a.source}</p><div className="notice">Cette fiche ne fournit pas d’horaires ou tarifs précis lorsqu’ils ne sont pas suffisamment vérifiés. Confirmez ces informations auprès de l’exploitant ou d’une source officielle avant votre déplacement.</div></section></div><div className="stack"><ActivityMap attraction={a}/>{city&&<Link className="btn green full" href={`/destinations/${city.slug}`}>Préparer un séjour à {city.name}</Link>}</div></div></main>}
